### ISSUE TITLE
Arrow tool no longer functions, spins the screenshot instead

### ISSUE THREAD

**Issue by nickdenardis** [TargetProcess/screen-capture-extension#5]
The arrow tool just stopped working, all other tools work fine. 

Example of what is happening on Chrome 41.0.2272.104 on OS X Yosemite:

![Rotate](http://media.giphy.com/media/3oEduZoEyKOm3MzCyA/giphy.gif)

**Comment by roadhump** [comment]
Fixed at version 1.1.6

**Comment by nickdenardis** [comment]
@roadhump Awesome thanks! All fixed now :smile:
